# Generated by Django 3.2 on 2022-03-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
