# Generated by Django 3.2 on 2022-03-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
